### ISSUE TITLE
denon [script name]  Doesn't kill app on reload

### ISSUE THREAD

**Issue by Trystan-SA** [denosaurs/denon#49]
I have a simple web server application running with oak. When I use the command `denon run --allow-net app.ts ` the auto reload successfully kill the webserver on each reload.

But when I use the `denon dev` command and using the denon.json file, the application isn't killed on each reload. For example, if I run the webserver on 8080 port, then change it to 8081 then save, I end up with 2 webserver. If I doesn't change the port between two save, I hand up with an error saying one app already use this port.

Here is my denon.json file 
![01](https://user-images.githubusercontent.com/43876044/82737622-8d229180-9d32-11ea-9fbf-725a62333def.PNG)

And my app.ts file
![02](https://user-images.githubusercontent.com/43876044/82737624-8eec5500-9d32-11ea-8535-879107bb713f.PNG)

**Comment by Qu4k** [comment]
In what os are you experiencing this issue?

**Comment by Trystan-SA** [comment]
Windows 10 Pro 64 bits
Version 10.0.17763

**Comment by Qu4k** [comment]
I can't seem to reproduce this issue on windows. Are you using the latest version of deno? (`v1.0.2`)

**Comment by Trystan-SA** [comment]
I'm using deno 1.0.2 and denon 2.0.0.
I deleted everything and rewrite only the part I give in my screenshots, same issue.

Here is the error log I got when I have two process running on the same port. The error is in French because my operating system is in French. It say "Only one usage of every socket port is authorised".

![01](https://user-images.githubusercontent.com/43876044/82741601-49d91a80-9d54-11ea-825f-4c6fa1b91419.PNG)

**Comment by eliassjogreen** [comment]
If you close down deno in the task manager and try again do you still get the error? I can't seem to reproduce it. What does your path look like?

**Comment by Trystan-SA** [comment]
Done it, nothing changed.
My path can be found on my last screen, 2nd line from below.

**Comment by meganyin13** [comment]
I am also having this issue on macOS Catalina using denon `v2.0.0` and deno `1.0.2` with my start script:
`"start": "denon run --allow-net --allow-read server/staticServer.ts"`
Interesting because just using `denon run` command on its own works fine. However, `denon [script]` doesn't close the app properly on reload.
Also seems that when we get this error the whole app crashes 😕

**Comment by Qu4k** [comment]
@meganyin13 
> "start": "denon run --allow-net --allow-read server/staticServer.ts"

Hi, I tested the project you linked in this issue with my Mac, adding:
```json
"scripts": {
  "start": "deno run --allow-net --allow-read server/staticServer.ts"
},
```
to the denon.json file. It seems to be working without any problems. 
- the one I used: `"start": "deno run --allow-net --allow-read server/staticServer.ts"`
- the one you provided: `"start": "denon run --allow-net --allow-read server/staticServer.ts"`

As you can see you are making denon run a `denon` command which spawns two daemons instead of a `deno` command.

**Comment by Qu4k** [comment]
@Trystan-SA 
Could you please try the new update (`denon --upgrade`). We fixed the issue for linux and macOS but we also added debug logs so we can look into this problem a bit more.
To enable debug logs please add this to your config file:
```json
{
  "logger": {
    "debug": true
   }
}
```
If the problem reoccurs please write a message here with all the stdout from denon. Thanks 🌟

**Comment by Trystan-SA** [comment]
Same problem, here is my console when I saved the same file without any port change (two reload on port 8080) :

![01](https://user-images.githubusercontent.com/43876044/82808188-c588b380-9e89-11ea-9542-63d3be20c4ec.PNG)


And then my console log when I saved the file when I changed the port to 8081 instead of 8080 :
![01](https://user-images.githubusercontent.com/43876044/82808561-80b14c80-9e8a-11ea-9edc-e3171716bd6e.PNG)

In the second test, the app never started on port 8081 (it crashed when I saved). But the app on the 8080 port is still running even after the crash.

**Comment by Qu4k** [comment]
With commit 2143585 I removed the faulty error message log.  Can you please `--upgrade` another time?

**Comment by Trystan-SA** [comment]
Still the same double port error...
![01](https://user-images.githubusercontent.com/43876044/82811483-2962aa80-9e91-11ea-8128-712442b0460a.PNG)

**Comment by Qu4k** [comment]
I have recreated your environment in a windows vm but I can't reproduce the issue.  If you have time come to our [discord server](https://discord.com/invite/shHG8vg) so we can have a faster way of communication.

**Comment by FarCryFromHuman** [comment]
I'm getting the socket in use error as well:

![image](https://user-images.githubusercontent.com/12355388/85956738-1ab25c00-b945-11ea-8690-99e2661e4edb.png)

And my denon.json file:
``` json
{
  "$schema": "https://deno.land/x/denon/schema.json",
  "scripts": {
    "start": {
      "cmd": "deno run server.ts",
      "allow": ["env", "net"],
      "desc": "run my app.ts file",
      "env": {
        "port": "8000"
      }
    }
  }
}
```

My versions:
![image](https://user-images.githubusercontent.com/12355388/85956770-5cdb9d80-b945-11ea-8666-66be261f2a42.png)

My OS info:
![image](https://user-images.githubusercontent.com/12355388/85956779-70870400-b945-11ea-9213-bd138187dc85.png)

**Comment by aaronwlee** [comment]
Local execution process.close() or self.close() are working well.
But if the execution path is coming from out of current dir, these two methods are causing this issue.

**Comment by eliassjogreen** [comment]
The current debug logs for this issue:
```
[*] [main] v2.4.4
[*] [daem] watching path(s): *.*
[*] [daem] watching extensions: ts,tsx,js,jsx,json
[!] [#0] starting `deno run -A ./main.ts`
[&] [#0] starting process with pid 3992
[&] [daem] monitoring status of process with pid 3992
[&] [path] trying to match denon.json
[&] [path] path denon.json is matched
[&] [path] trying to match denon.json
[&] [path] path denon.json is matched
[&] [daem] reload event detected, starting the reload procedure...
[&] [main] reloading config
[*] [daem] restarting due to changes...[&] [daem] killing 1 orphan process[es]
[&] [daem] closing (windows) process with pid 3992      
[*] [daem] watching path(s): *.*
[*] [daem] watching extensions: ts,tsx,js,jsx,json      
[!] [#0] starting `deno run -A ./main.ts`
[&] [#0] starting process with pid 18220
[&] [daem] monitoring status of process with pid 18220  
[&] [daem] error getting status of process with pid 3992
[&] [daem] process with pid 3992 was killed
error: Uncaught AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
    at processResponse (core.js:226:13)
    at Object.jsonOpSync (core.js:250:12)
    at opListen (deno:cli/rt/30_net.js:32:17)
    at Object.listen (deno:cli/rt/30_net.js:207:17)
    at Application.serve (server.ts:287:25)
    at Application.listen (application.ts:362:20)
    at main.ts:9:11
[&] [daem] got status of process with pid 18220
[&] [daem] process with pid 18220 exited on its own
[E] [daem] app crashed - waiting for file changes before starting ...
```

**Comment by eliassjogreen** [comment]
Most likely related to [deno#7824](https://github.com/denoland/deno/issues/7824)

**Comment by fauzan121002** [comment]
I'm also getting this issue by Oak Server , can somebody help?

**Comment by fauzan121002** [comment]
```bash
error: Uncaught AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
    at unwrapResponse (rt/10_dispatch_json.js:24:13)
    at sendSync (rt/10_dispatch_json.js:51:12)
    at opListen (rt/30_net.js:33:12)
    at Object.listen (rt/30_net.js:204:17)
    at Object.listen (rt/40_net_unstable.js:11:18)
    at Application.serve (server.ts:287:25)
    at Application.listen (application.ts:363:20)
    at Server.run (file:///B:/projek-deno/denovel/vendor/Denovel/mod.ts:15:1)
    at file:///B:/projek-deno/denovel/server.ts:3:1
    at <anonymous> (<anonymous>)
[E] [daem] app crashed - waiting for file changes before starting ...
```

I'm also getting this issue while using oak server with denon. 

PS: I use deno v1.3.1 and windows 10

**Comment by mooxl** [comment]
Hey, guys,
I do not know, if it is related to the fact, that denon does not kill the previous instance, but I have the same problem, that the adress is already used. I have deno or denon running in a docker container and every time I change a file in the root folder denon is executed once more than before. See logs
`deno_dev_1  | [*] [main] v2.4.4
deno_dev_1  | [*] [daem] watching path(s): *.*
deno_dev_1  | [*] [daem] watching extensions: ts,tsx,js,jsx,json
deno_dev_1  | [!] [#0] starting `denon start`
deno_dev_1  | [*] [main] v2.4.4
deno_dev_1  | [*] [daem] watching path(s): *.*
deno_dev_1  | [*] [daem] watching extensions: ts,tsx,js,jsx,json
deno_dev_1  | [!] [#0] starting `deno run --allow-env --allow-net --unstable main.ts`
deno_dev_1  | Server running on port 3000
deno_dev_1  | [*] [daem] restarting due to changes...
deno_dev_1  | [*] [daem] watching path(s): *.*
deno_dev_1  | [*] [daem] watching extensions: ts,tsx,js,jsx,json
deno_dev_1  | [!] [#0] starting `denon start`
deno_dev_1  | [*] [daem] restarting due to changes...
deno_dev_1  | [*] [daem] watching path(s): *.*
deno_dev_1  | [*] [daem] watching extensions: ts,tsx,js,jsx,json
deno_dev_1  | [!] [#0] starting `deno run --allow-env --allow-net --unstable main.ts`
deno_dev_1  | [*] [main] v2.4.4
deno_dev_1  | [*] [daem] watching path(s): *.*
deno_dev_1  | [*] [daem] watching extensions: ts,tsx,js,jsx,json
deno_dev_1  | [!] [#0] starting `deno run --allow-env --allow-net --unstable main.ts`
deno_dev_1  | Server running on port 3000
deno_dev_1  | Server running on port 3000
deno_dev_1  | error: Uncaught AddrInUse: Address already in use (os error 98)
deno_dev_1  |     at Object.jsonOpSync (core.js:247:13)
deno_dev_1  |     at opListen (deno:cli/rt/30_net.js:32:17)
deno_dev_1  |     at Object.listen (deno:cli/rt/30_net.js:207:17)
deno_dev_1  |     at Object.listen (deno:cli/rt/40_net_unstable.js:11:18)
deno_dev_1  |     at Application.serve (server.ts:287:25)
deno_dev_1  |     at Application.listen (application.ts:362:20)
deno_dev_1  |     at main.ts:12:11
deno_dev_1  |     at <anonymous> (<anonymous>)
deno_dev_1  | [E] [daem] app crashed - waiting for file changes before starting ...
deno_dev_1  | [*] [daem] restarting due to changes...
deno_dev_1  | [*] [daem] watching path(s): *.*
deno_dev_1  | [*] [daem] watching extensions: ts,tsx,js,jsx,json
deno_dev_1  | [!] [#0] starting `deno run --allow-env --allow-net --unstable main.ts`
deno_dev_1  | [*] [daem] restarting due to changes...
deno_dev_1  | [*] [daem] watching path(s): *.*
deno_dev_1  | [*] [daem] watching extensions: ts,tsx,js,jsx,json
deno_dev_1  | [!] [#0] starting `deno run --allow-env --allow-net --unstable main.ts`
deno_dev_1  | [*] [daem] restarting due to changes...
deno_dev_1  | [*] [daem] watching path(s): *.*
deno_dev_1  | [*] [daem] watching extensions: ts,tsx,js,jsx,json
deno_dev_1  | [!] [#0] starting `denon start`
deno_dev_1  | Server running on port 3000
deno_dev_1  | Server running on port 3000
deno_dev_1  | error: Uncaught AddrInUse: Address already in use (os error 98)
deno_dev_1  |     at Object.jsonOpSync (core.js:247:13)
deno_dev_1  |     at opListen (deno:cli/rt/30_net.js:32:17)
deno_dev_1  |     at Object.listen (deno:cli/rt/30_net.js:207:17)
deno_dev_1  |     at Object.listen (deno:cli/rt/40_net_unstable.js:11:18)
deno_dev_1  |     at Application.serve (server.ts:287:25)
deno_dev_1  |     at Application.listen (application.ts:362:20)
deno_dev_1  |     at main.ts:12:11
deno_dev_1  |     at <anonymous> (<anonymous>)
deno_dev_1  | [E] [daem] app crashed - waiting for file changes before starting ...
deno_dev_1  | [*] [main] v2.4.4
deno_dev_1  | [*] [daem] watching path(s): *.*
deno_dev_1  | [*] [daem] watching extensions: ts,tsx,js,jsx,json
deno_dev_1  | [!] [#0] starting `deno run --allow-env --allow-net --unstable main.ts`
deno_dev_1  | Server running on port 3000
deno_dev_1  | error: Uncaught AddrInUse: Address already in use (os error 98)
deno_dev_1  |     at Object.jsonOpSync (core.js:247:13)
deno_dev_1  |     at opListen (deno:cli/rt/30_net.js:32:17)
deno_dev_1  |     at Object.listen (deno:cli/rt/30_net.js:207:17)
deno_dev_1  |     at Object.listen (deno:cli/rt/40_net_unstable.js:11:18)
deno_dev_1  |     at Application.serve (server.ts:287:25)
deno_dev_1  |     at Application.listen (application.ts:362:20)
deno_dev_1  |     at main.ts:12:11
deno_dev_1  |     at <anonymous> (<anonymous>)
deno_dev_1  | [E] [daem] app crashed - waiting for file changes before starting ...`

**Comment by xsonic** [comment]
Same Problem on Windows 10 Pro.

`E:\www\test\deno-test-1>denon start
[*] [main] v2.4.4
[*] [daem] watching path(s): *.*
[*] [daem] watching extensions: ts,tsx,js,jsx,json
[!] [#0] starting `deno run -A index.ts`
[&] [#0] starting process with pid 18016
[&] [daem] monitoring status of process with pid 18016
[&] [path] trying to match index.ts
[&] [path] path index.ts is matched
[&] [path] trying to match index.ts
[&] [path] path index.ts is matched
[&] [path] trying to match .idea\workspace.xml
[&] [path] path .idea\workspace.xml does not have right extension
[&] [path] trying to match .idea\workspace.xml
[&] [path] path .idea\workspace.xml does not have right extension
[&] [daem] reload event detected, starting the reload procedure...
[*] [daem] restarting due to changes...
[&] [daem] killing 1 orphan process[es]
[&] [daem] closing (windows) process with pid 18016
[*] [daem] watching path(s): *.*
[*] [daem] watching extensions: ts,tsx,js,jsx,json
[!] [#0] starting `deno run -A index.ts`
[&] [#0] starting process with pid 14788
[&] [daem] monitoring status of process with pid 14788
[&] [daem] error getting status of process with pid 18016
[&] [daem] process with pid 18016 was killed
Check file:///E:/www/test/deno-test-1/index.ts
error: Uncaught AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
    at processResponse (core.js:226:13)
    at Object.jsonOpSync (core.js:250:12)
    at opListen (deno:cli/rt/30_net.js:32:17)
    at Object.listen (deno:cli/rt/30_net.js:207:17)
    at Application.serve (server.ts:287:25)
    at Application.listen (application.ts:362:20)
    at index.ts:27:11
[&] [daem] got status of process with pid 14788
[&] [daem] process with pid 14788 exited on its own
[E] [daem] app crashed - waiting for file changes before starting ...
`

deno 1.4.6
v8 8.7.220.3
typescript 4.0.3
denon 2.4.4

**Comment by topstop3416** [comment]
![denon-error-10048](https://user-images.githubusercontent.com/37021873/97966716-30ee8e00-1df7-11eb-9ea7-c92c4fad653e.png)

> {
  "$schema": "https://deno.land/x/denon/schema.json",
  "scripts": {
    "start": {
      "cmd": "deno run -A ./src/app.ts",
      "desc": "run my app.ts file"
    }
  },
  "watcher": { "match": ["**/*.*"] },
  "logger": {
    "debug": true
  }
}


> deno 1.5.1
v8 8.7.220.3
typescript 4.0.3

**Comment by MustachedNinja** [comment]
I had a similar issue to this. I made a simple oak server which just returns "Hello World" and whenever I would make a change and restart the server, I would get the AddrInUse error

My Code:
======

server.ts
``` typescript
import * as log from "https://deno.land/std@0.77.0/log/mod.ts";
import { Application, Router, RouterContext } from "https://deno.land/x/oak@v6.3.2/mod.ts";

const app = new Application();
const router = new Router();

router.get('/', (ctx: RouterContext) => {
    ctx.response.body = "Hello World";
});

app.use(router.routes());
app.use(router.allowedMethods());

app.addEventListener('listen', ({ hostname, port, secure }) => {
    log.info(`Listening on ${secure ? 'https://' : 'http://'}${hostname || "localhost"}:${port}`)
});

await app.listen({ port: 3000 });
```

scripts.json 
``` json
{
  "$schema": "https://deno.land/x/denon/schema.json",
  "scripts": {
    "start": {
      "cmd": "deno run server.ts",
      "allow": ["net"],
      "desc": "run my app.ts file"
    }
  },
  "logger": {
    "quiet": false,
    "debug": true
  }
}
```

Error Log:
========

``` cmd
[*] [main] v2.4.4
[*] [daem] watching path(s): *.*
[*] [daem] watching extensions: ts,tsx,js,jsx,json
[!] [#0] starting `deno run --allow-net server.ts`
[&] [#0] starting process with pid 17392
[&] [daem] monitoring status of process with pid 17392
Listening on http://localhost:3000
[&] [path] trying to match server.ts
[&] [path] path server.ts is matched
[&] [path] trying to match server.ts
[&] [path] path server.ts is matched
[&] [daem] reload event detected, starting the reload procedure...
[*] [daem] restarting due to changes...
[&] [daem] killing 1 orphan process[es]
[&] [daem] closing (windows) process with pid 17392
[*] [daem] watching path(s): *.*
[*] [daem] watching extensions: ts,tsx,js,jsx,json
[!] [#0] starting `deno run --allow-net server.ts`
[&] [#0] starting process with pid 15416
[&] [daem] monitoring status of process with pid 15416
[&] [daem] error getting status of process with pid 17392
[&] [daem] process with pid 17392 was killed
Check file:///C:/Users/{{USER}}/Programming/Deno/survey-app/server.ts
error: Uncaught AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
    at processResponse (core.js:224:13)
    at Object.jsonOpSync (core.js:248:12)
    at opListen (deno:cli/rt/30_net.js:32:17)
    at Object.listen (deno:cli/rt/30_net.js:207:17)
    at Application.serve (server.ts:287:25)
    at Application.listen (application.ts:362:20)
    at server.ts:17:11
[&] [daem] got status of process with pid 15416
[&] [daem] process with pid 15416 exited on its own
[E] [daem] app crashed - waiting for file changes before starting ...
```

What I did:
=======

I decided to try and figure out what the issue was by pulling the code from the github repo and modifying it locally. After pulling, I took a quick look over the code and ran `deno install --unstable --allow-read --allow-write --allow-run -f denon.ts`. I verified that I was getting version 2.4.4, and tried running `denon start` on my project and tried restarting the project as usual, and it succeeded:

``` cmd
C:\Users\{{USER}}\Programming\Deno\survey-app>denon start
[*] [main] v2.4.4
[*] [daem] watching path(s): **/*.*
[*] [daem] watching extensions: ts,tsx,js,jsx,json
[!] [#0] starting `deno run --allow-net server.ts`
[&] [#0] starting process with pid 23148
[&] [daem] monitoring status of process with pid 23148
INFO Listening on http://localhost:3000
[&] [path] trying to match server.ts
[&] [path] path server.ts is matched
[&] [path] trying to match server.ts
[&] [path] path server.ts is matched
[&] [daem] reload event detected, starting the reload procedure...
[*] [daem] restarting due to changes...
[&] [daem] killing 1 orphan process[es]
[&] [daem] closing (windows) process with pid 23148
[*] [daem] watching path(s): **/*.*
[*] [daem] watching extensions: ts,tsx,js,jsx,json
[!] [#0] starting `deno run --allow-net server.ts`
[&] [#0] starting process with pid 21312
[&] [daem] monitoring status of process with pid 21312
[&] [daem] error getting status of process with pid 23148
[&] [daem] process with pid 23148 was killed
Check file:///C:/Users/{{USER}}/Programming/Deno/survey-app/server.ts
INFO Listening on http://localhost:3000
[&] [path] trying to match server.ts
[&] [path] path server.ts is matched
[&] [path] trying to match server.ts
[&] [path] path server.ts is matched
[&] [daem] reload event detected, starting the reload procedure...
[*] [daem] restarting due to changes...
[&] [daem] killing 1 orphan process[es]
[&] [daem] closing (windows) process with pid 21312
[*] [daem] watching path(s): **/*.*
[*] [daem] watching extensions: ts,tsx,js,jsx,json
[!] [#0] starting `deno run --allow-net server.ts`
[&] [#0] starting process with pid 15332
[&] [daem] monitoring status of process with pid 15332
[&] [daem] error getting status of process with pid 21312
[&] [daem] process with pid 21312 was killed
Check file:///C:/Users/{{USER}}/Programming/Deno/survey-app/server.ts
INFO Listening on http://localhost:3000
```

**Comment by dennisschott** [comment]
Still the same os error 10048 on Windows 10 Pro with Denon v2.4.4 :(

Windows 10 Pro 20H2
Deno 1.5.2
Denon 2.4.4

**Comment by Tzahile** [comment]
I get this bug too,
win10
deno 1.5.3
denon 2.4.5

@MustachedNinja Can you offer a PR to fix this issue?

I noticed this bug happens when I set a `scripts.config.ts`.
After deleting `scripts.config.ts` file and running `denon run .\src\index.ts` again, denon didn't crash on save.

```ts
// scripts.config.ts
import { DenonConfig } from "https://deno.land/x/denon/mod.ts";

const config: DenonConfig = {
  env: {
    DENO_DIR: "./deno_dir",
  },

  scripts: {
    cache: {
      cmd: "deno cache src/index.ts --lock-write",
      desc: "Caches all deps and locks them in .lock file",
      lock: "./lock.json",
      watch: false,
    },
    serve: {
      cmd: "deno run src/index.ts",
      desc: "run my app.ts file in DEV mode",
      watch: true,
      allow: {
        net: true,
      },
      env: {
        DEV: "true",
      },
    },

    start: {
      cmd: "deno run src/index.ts",
      desc: "run my app.ts file in PROD mode",
      allow: {
        net: true,
      },
      watch: false,
    },
  },
  watcher: {
    exts: ["js", "ts", "json"],
    match: ["src/**/*.*"],
    skip: ["./lock.json"],
  },
};

export default config;

```

**Comment by MustachedNinja** [comment]
I finally had some free time to take a look at the bug, and it looks like it was patched in version 2.4.5
When you're installing, change their default install text to use version 2.4.5 instead of 2.4.4, and it should work. I tried a fresh install of denon 2.4.5 with deno 1.5.2 and it restarts just fine now.

**Comment by dennisschott** [comment]
I can confirm, that it works with 2.4.5 on W10.

**Comment by MikaelPorttila** [comment]
Having this issue on Win 10 LTSC, Deno 1.6.2 and Denon 2.4.5:

![image](https://user-images.githubusercontent.com/903468/103156597-689c0580-47aa-11eb-88b8-1d1dc31104a4.png)

**Comment by Conando025** [comment]
Having the same issue also with Win 10, Deno 1.6.2, Denon 2.4.5

**Comment by Skitch90** [comment]
Same issue with 
- Windows 10 Home (version	20H2, build 19042.685)
- Deno 1.6.3
- Denon 2.4.5

**Comment by dale-roberts** [comment]
I have also confirmed this to still be a problem, using **Windows 10, Deno 1.6.3, and Denon 2.4.5**. I believe the problem is that when the killAll() routine in deamon.ts calls **p.close()** under Windows, this is not actually killing the process. Can confirm this with ProcessExplorer, and see that the original process ID is never killed, and subsequent processes die due to the Socket reuse error.

I'm not a Github guru, so I'm just posting my small change here, adding **p.kill()** to the Windows case, which fixes the problem for me.

```typescript
if (Deno.build.os === "windows") {
     logger.debug(`closing (windows) process with pid ${p.pid}`);
     p.close(); // This original line does NOT end the process.
     p.kill(9); // <<<<<< This added line DOES end the Windows process.
} else {
     logger.debug(`killing (unix) process with pid ${p.pid}`);
     p.kill(9);
}
```

Could also just get rid of the whole "if" and use kill() always. But I'm sure p.close() was added specially for Windows for some reason, and based on other reports here it seems to sometimes work, so I'm not sure why it is not working for all of us. I'm also not sure whether kill() has any bad/unintended effects in Windows.

**Comment by MustachedNinja** [comment]
Thanks @dale-roberts , I submitted a pull request for your suggestion: #120

**Comment by kelvin0712** [comment]
Hi, I am not sure about the reason but I am still having this problem on `Window 10 Pro, Denon: 2.4.7` and I just have a simple config. 
![image](https://user-images.githubusercontent.com/45527642/114954891-d4f85d00-9e9e-11eb-8ad6-293a7c859e08.png)

**Comment by ablause** [comment]
Hi, I have the same problem again. I have tested several startup configurations but nothing works.
I use **Deno 1.9.0, Denon 2.4.7 and Windows 10 Pro** (build: 21359.1).

Furthermore, I also tried to downgrade **Deno to 1.6.3**, but I have another error: 
`
error: TS2339 [ERROR]: Property 'host' does not exist on type 'NetPermissionDescriptor'.
              return pd.host
                        ~~~~
    at https://deno.land/std@0.85.0/permissions/mod.ts:17:25

TS2339 [ERROR]: Property 'host' does not exist on type 'NetPermissionDescriptor'.
                ? `--allow-${pd.name}=${pd.host}`
                                           ~~~~
    at https://deno.land/std@0.85.0/permissions/mod.ts:18:44

Found 2 errors.
`

**Comment by Trystan-SA** [comment]
Same problem than last year. Deno 1.9.0. Denon 2.4.7. Windows 10 Pro (1.0.0.19041)

**scripts.json**
```json
 {
    "$schema": "https://cdn.deno.land/denon/versions/2.4.7/raw/schema.json",
    "scripts": {

        "dev":{
            "watch": true,
            "allow": ["net", "read", "write", "env"],
            "cmd": "deno run --unstable ./Server/Server.ts",
            "log": "info",
            "env": {
                "isdev":"dev"
            }
        },


        "compile": {
            "watch": false,
            "cmd": "deno compile --unstable --allow-net --allow-read --allow-write --allow-env ./Server/Server.ts"
        }
    },

    "watcher": {
        "interval": 500,
        "exts": [
            "ts",
            "tsx",
            "json"
        ]
    }
}
```


**Server.ts**
```js
import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use(async (context)=>{
    await context.send({
        root: `${Deno.cwd()}/Client/Dist/`,
        index: 'index.html'
    })
})

console.log("App listening to http://localhost:8080")
await app.listen("localhost:8080");
```


**Console screen (first launch & reload with save)**

![01](https://user-images.githubusercontent.com/43876044/115117163-81b90400-9f9d-11eb-95bb-6659e16b6a83.PNG)

**Comment by ablause** [comment]
The error occurs only with Oak for me. I tried to compare other HTTP modules, but I can't find anything strange. The process closes every other time.

With the command `deno run --watch ${script}`, everything works fine. Couldn't Denon use the Deno functionality directly?

**Comment by Trystan-SA** [comment]
For me it also occurs with the built-in deno http module (and with oak too). 

I finished by writing my own watch script like so :

```js
const watcher = Deno.watchFs("./Server");
let LastReload : Date = new Date();

let Process : Deno.Process
Launch_Process()

for await (const event of watcher){
    if((LastReload.getTime() + 1000) < new Date().getTime()){
        LastReload = new Date()

        Kill_Process()
        Launch_Process()
    
    }
}


function Launch_Process(){
    Process = Deno.run({
        cmd: ["deno", "run", "--unstable", "-A", "Server/Server.ts"]
    }) 
}

function Kill_Process(){Process.close()}
```

And everything work well now.

**Comment by MustachedNinja** [comment]
@Trystan-SA can you post either the http server or oak server that you wrote which causes the issue to appear? I've been unable to replicate the issue on my machine (using Deno 1.9.0 and Denon 2.4.7 on Windows)

**Comment by MustachedNinja** [comment]
@Trystan-SA I'm having trouble recreating your issue on my machine using the same setup. Did you try force-reinstalling denon?
